### ISSUE TITLE
Implementing Continuous integration into the program using the Travis CI Service. 

### ISSUE THREAD

**Issue by DoublePlusGood23** [Quantum-Code/deprecated-derby-manager#11]
I'll attempt to write unit tests for the current code base, but I'll also need everyone else to ensure their code is covered. 

@garretyoder shouldn't be too concerned until I try implementing various UI regression tests. @azharichenko You will likely need to go back and write tests, otherwise ensure your code is commented well.

We're using Travis CI for the time being to make it easier for others commit and no need to worry about downtime. 

You can follow my progress on the dev/ci branch.

Happy Hacking.

**Comment by azharichenko** [comment]
Agreed but next time don't make the title so long. But yeah we should branch off of dev when we need to add a new feature onto dev itself
