### ISSUE TITLE
Contribution file 

### ISSUE THREAD

**Issue by DoublePlusGood23** [Quantum-Code/deprecated-derby-manager#5]
Can you add a CONTRIBUTING file to clear up the proper way to commit? 

I'm not currently sure if I should contribute on `dev` or if I should branch off `dev` and make a `dpg` branch.

Add in GPG signing to :smile:

**Comment by azharichenko** [comment]
Just started and created the CONTRIBUTION.md file. We just need to fill out the content inside of it
